{
  description = "agentmemory - Persistent memory for AI coding agents";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

  outputs = { self, nixpkgs }:
    let
      systems = [ "x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin" ];
      forAllSystems = nixpkgs.lib.genAttrs systems;

      version = "0.9.26";

      # Fetch pre-built npm tarball (avoids building TypeScript from source).
      # Get the real npmDepsHash:
      #   1. Set npmDepsHash to lib.fakeHash
      #   2. Run: nix build "path:...#default"
      #   3. Replace with the hash from the error message
      npmDepsHash = "sha256-0aWXHpP31ZmHtJ3dYqHr/sQoKNy5azmUmosyMUdY7RE=";

      # ── iii-engine runtime ───────────────────────────────────────
      # Pre-built Rust binary from GitHub releases. Downloaded here
      # rather than via a flake input to avoid path-input eval issues.
      # Pinned to v0.11.2 — agentmemory currently locks this version.
      iiiVersion = "0.11.2";
      systemToAsset = {
        "x86_64-linux"    = "x86_64-unknown-linux-gnu";
        "aarch64-linux"   = "aarch64-unknown-linux-gnu";
        "x86_64-darwin"   = "x86_64-apple-darwin";
        "aarch64-darwin"  = "aarch64-apple-darwin";
      };
      iiiHashes = {
        "x86_64-linux"    = "sha256-nIPEd4i070vutl3ZvzfpT5k3cM09uHRGTDzhzckjUs0=";
        "aarch64-linux"   = "";
        "x86_64-darwin"   = "";
        "aarch64-darwin"  = "";
      };
    in
    {
      packages = forAllSystems (system:
        let
          pkgs = nixpkgs.legacyPackages.${system};

          # Embedded iii-engine derivation (avoids cross-flake input dependency)
          iii = pkgs.stdenvNoCC.mkDerivation {
            pname = "iii-engine";
            version = iiiVersion;

            src = pkgs.fetchurl {
              url = "https://github.com/iii-hq/iii/releases/download/iii/v${iiiVersion}/iii-${systemToAsset.${system} or "x86_64-unknown-linux-gnu"}.tar.gz";
              hash = iiiHashes.${system} or pkgs.lib.fakeHash;
            };

            dontUnpack = true;

            installPhase = ''
              runHook preInstall
              mkdir -p $out/bin
              tar -xzf $src -C $out/bin iii
              chmod +x $out/bin/iii
              runHook postInstall
            '';

            dontFixup = true;

            meta.description = "iii-engine runtime (embedded for agentmemory)";
          };

          src = pkgs.fetchurl {
            url = "https://registry.npmjs.org/@agentmemory/agentmemory/-/agentmemory-${version}.tgz";
            #hash = pkgs.lib.fakeHash;
            hash = "sha256-h6SMbE4ELw91wQEh+zEJZ8XOd67+kWRbDXh6VWQdRTI=";
          };

          # Pre-fetch only production dependencies (no devDeps, no TypeScript build).
          # npm tarball ships pre-built dist/ — no build step needed.
          npmDeps = pkgs.fetchNpmDeps {
            name = "agentmemory-npm-deps";
            inherit src;
            sourceRoot = "package";
            hash = npmDepsHash;
            # cacert needed for SSL cert validation in npm
            nativeBuildInputs = [ pkgs.nodejs_22 pkgs.cacert ];

            # NOTE: generates lockfile with ALL deps (dev included) so fetchNpmDeps
            # caches the full transitive tree. npmInstallFlags below restricts to
            # production deps at install time.
            postPatch = ''
              HOME=$TMPDIR npm install --package-lock-only --ignore-scripts --legacy-peer-deps --no-audit --no-fund
            '';
          };
        in
        {
          default = pkgs.buildNpmPackage {
            pname = "agentmemory";
            inherit version src npmDeps;

            # npm tarball has package/ prefix
            sourceRoot = "package";

            # Already pre-built — just need runtime deps from npmDeps
            dontBuild = true;

            # Only install production deps (devDeps are only needed for lockfile gen)
            npmInstallFlags = [ "--production" ];

            # Avoid peer dep conflicts during install
            npmFlags = [ "--legacy-peer-deps" ];

            # Skip rebuild scripts — sharp's install downloads libvips from GitHub
            # and fails in the sandbox. Only needed for optional onnx dep anyway.
            npmRebuildFlags = [ "--ignore-scripts" ];

            # npm needs to write to cache during install
            makeCacheWritable = true;

            # npm tarball doesn't ship package-lock.json (it's generated by
            # fetchNpmDeps' postPatch). Copy it so npmConfigHook can validate.
            postPatch = ''
              cp ${npmDeps}/package-lock.json package-lock.json
            '';

            nodejs = pkgs.nodejs_22;

            nativeBuildInputs = [ pkgs.makeWrapper ];

            installPhase = ''
              runHook preInstall

              mkdir -p $out/lib/node_modules/@agentmemory/agentmemory
              cp -r dist package.json node_modules $out/lib/node_modules/@agentmemory/agentmemory/
              cp -r iii-config.yaml docker-compose.yml .env.example \
                $out/lib/node_modules/@agentmemory/agentmemory/ 2>/dev/null || true
              [ -d plugin ] && cp -r plugin $out/lib/node_modules/@agentmemory/agentmemory/

              mkdir -p $out/bin
              makeWrapper ${pkgs.nodejs_22}/bin/node \
                $out/bin/agentmemory \
                --prefix PATH : ${iii}/bin \
                --add-flags "$out/lib/node_modules/@agentmemory/agentmemory/dist/cli.mjs"

              runHook postInstall
            '';

            meta = with pkgs.lib; {
              description = "Persistent memory for AI coding agents";
              longDescription = ''
                agentmemory provides persistent memory for AI coding agents.
                It silently captures what your agent does, compresses it into
                searchable memory, and injects the right context when the next
                session starts. Built on iii-engine primitives.
              '';
              homepage = "https://github.com/rohitg00/agentmemory";
              license = licenses.asl20;
              mainProgram = "agentmemory";
              platforms = systems;
              maintainers = [ ];
            };
          };
        }
      );
    };
}
